server:
    servlet:
        context-path: /hikari

spring:
    ########-oracle数据库链接配置-########
    datasource:
        url: jdbc:oracle:thin:@172.17.209.243:1521:bidbportal
        username: u_db_pt
        password: u_db_pt
        driver-class-name: oracle.jdbc.driver.OracleDriver
        type: com.zaxxer.hikari.HikariDataSource  #连接hikari数据源
        #hikari数据库连接池
        hikari:
            ################常用配置如下###################
            #连接池名字，主要出现在日志记录和JMX管理控制台中以识别池和池配置。 默认：自动生成
            pool-name: MY_FIRST_HikariCP
            #最小空闲连接数，为了获得最佳性能和响应尖峰需求，我们建议不要设置此值，而是允许HikariCP充当固定大小的连接池。 默认值：与maximumPoolSize相同
            minimum-idle: 5
            #空闲连接存活最大时间，默认600000（10分钟），值为0意味着空闲连接永远不会从池中删除。允许的最小值是10000ms（10秒）
            idle-timeout: 180000
            #连接池最大连接数，包括空闲和正在使用的连接，默认是10，当池达到此大小并且没有空闲连接可用时，对getConnection（）的调用将connectionTimeout在超时前阻塞达几毫秒
            maximum-pool-size: 10
            #是否自动提交事务,默认值：true
            auto-commit: true
            #池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟 ，超时而且没被使用则被释放（retired）
            max-lifetime: 1800000
            #控制客户端将等待来自池的连接的最大毫秒数。如果在没有可用连接的情况下超过此时间，则会抛出SQLException。最低可接受的连接超时时间为250 ms。 默认值：30000（30秒）
            connection-timeout: 30000
            #连接池每分配一个连接前执行的查询语句（如：SELECT 1），以验证该连接是否是有效的，如果你的驱动程序支持 JDBC4，HikariCP 强烈建议我们不要设置此属性。如果设置的话，mysql和oracle的配置是不一样的，oracle为select 1 from dual，mysql为select 1
            connection-test-query: SELECT 1 FROM DUAL
            data-source-properties:
                #是否自定义配置，为true时下面两个参数才生效
                cachePrepStmts: true
                #连接池大小默认25，官方推荐250-500
                prepStmtCacheSize: 250
                #单条语句最大长度默认256，官方推荐2048
                prepStmtCacheSqlLimit: 2048

mybatis:
    #mybatis映射文件xml的路径
    mapperLocations: classpath*:mapper/*Mapper.xml
    #实体类所在包路径 
    type-aliases-package: com.sample.test.common.entity
